### ISSUE TITLE
Async schema definition support

### ISSUE THREAD

**Issue by airhorns** [enisdenjo/graphql-ws#127]
### Story

It'd be great to support passing a `Promise<GraphQLSchema>` instead of just a `GraphQLSchema` object to `useServer` and friends. This would support fancy use cases like dynamically generated GraphQL schemas for things like federation or the fancy database-to-graphql tooling.

The reason why it'd be necessary to support async schema as an option in this library instead of having it all be done in userland is that the GraphQL subscriptions server needs to synchronously register `on('message')` handlers with the websocket to receive the init messages and other setup stuff, and then `await` the schema inside itself once operations start.

If instead a user asynchronously built a schema on connection, and then got a server set up to handle the connection, there's a brief but very real moment after when the `ws` library (or whatever) has established the websocket connection and is accepting messages but before the message handlers are set up by `graphql-ws` to listen for those messages and respond to them.
 
I think this is a super niche use case, but I'd love to highlight it anyways to see you fine folks would be interested in PRs adding this functionality. Also, I think that you might be able to get something like this working by returning a promise for `ExecutionArgs` with an asynchronously built schema in the `onSubscribe` option, but my reading of the docs suggests this would only work for subscriptions, and not the other operation types, which would be great to get support for as well.

### Acceptance criteria

- A developer should be able to pass a `GraphQLSchema` or a promise for a `GraphQLSchema` into the `schema` property for a `makeServer` or `useServer`.

**Comment by n1ru4l** [comment]
Instead of making each option a function that can potentially return a Promise, why not combine all the things that could differentiate based on the incoming operation?

I did this over here with my Socket.is transport https://github.com/n1ru4l/graphql-live-query/blob/4a6fe0f1925b72abb60f8f1f301fdb22f4794455/packages/socket-io-graphql-server/src/registerSocketIOGraphQLServer.ts#L48

**Comment by enisdenjo** [comment]
You can already pass in a custom schema on every operation using [the `onSubscribe` server option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.serveroptions.md#onsubscribe). Note that `onSubscribe` is for _all_ possible operations (not just subscriptions), the "subscribe" is meant to represent a client subscribing to data.

`onSubscribe` can return a promise which resolves to either `ExecutionArgs` which are plugged in to GraphQL's `execute` or `subscribe` function (depending on the operation type), or `GraphQLError[]` for reporting GQL errors through the `ErrorMessage`. Inside the `ExecutionArgs` you may provide any schema you want and since `onSubscribe` is async compatible, you can achieve what you wish for - from persisted queries to dynamically built schemas.

You may find the [server usage with custom execution arguments and validation recipe](https://github.com/enisdenjo/graphql-ws#custom-exec) helpful.

**Comment by airhorns** [comment]
Ok -- I didn't realize it applied to all operations, my bad! 

Is there a way to re-use the default execution args logic such that I don't have to reimplement or copy paste the `graphql-ws` internals that produce execution args from the message? Right now, it's only the schema that I want to override and I would like to be on the upgrade train for the rest of the logic to produce the args for `execute`.

**Comment by enisdenjo** [comment]
The provided recipe showcases a proper custom `onSubscribe` implementation.

It extracts the relevant details from the payload, formats it correctly to `ExecutionArgs` and validates them. This is all you really need.

Just pluck in your schema and you're good to go!

**Comment by airhorns** [comment]
Ok, it makes me a touch nervous to couple to a bunch of GraphQL fundamentals there (like how errors are produced) but I think that isn't the end of the world and I very much appreciate the flexibility built in. Thanks for an awesome library Denis!

**Comment by enisdenjo** [comment]
Well, whenever you want to execute a GQL query you have to formulate the exec args and validate them - you're not fiddling with internals a lot. But, as you mentioned, its the flexibility that I want to offer which is why you have to do this yourself if you decide not to use the built-ins.

Oh and, you're very welcome! I am glad you like it. 😄

**Comment by enisdenjo** [comment]
@airhorns 👋, starting from [`v4.3.0`](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.3.0), [the server `schema` option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.serveroptions.md#schema) accepts a function or a Promise. What your issue describes can be now achieved a tad easier.

**Comment by airhorns** [comment]
Whoopee! Thanks!
