### ISSUE TITLE
"Socket closed with event 1011 Schema is not configured for mutations." on Mutations

### ISSUE THREAD

**Issue by c4c1us** [enisdenjo/graphql-ws#142]
Hi, 

First of this package is great !

But why can't  I  use mutations ?

I received this error `"Socket closed with event 1011 Schema is not configured for mutations."`

Thanks

**Comment by enisdenjo** [comment]
Hey there, thanks! 😄

I recon that the error `Schema is not configured for mutations` originates from your GraphQL setup; not caused by `graphql-ws`, it is just the mediator.

[A Google search yields many results for the error message](https://www.google.com/search?q=Schema+is+not+configured+for+mutations), maybe some of them can help?

Also, would be great if you could share the schema too?

**Comment by c4c1us** [comment]
Hi again,

I'm embarrassed, It was a typing error..
I did see theses Google results before but I didn't see my mistake the first time.

Sorry for blaming your package and wasting your time !

Have a nice day!

**Comment by enisdenjo** [comment]
Thats ok, glad you solved it!
