### ISSUE TITLE
Q: Protocol compatibility with subscriptions-transport-ws

### ISSUE THREAD

**Issue by spencerwilson** [enisdenjo/graphql-ws#154]
Hi. First, thanks for your significant investment in GraphQL over WebSockets. 🙇‍♂️ Background: I'm the maintainer of an application serving an apollo-server@2.21.0 API and am seeking to understand the specific protocols my application serves, and which GraphQL clients are [or are extensible enough to be able to be made] compatible with us. AFAICT our Apollo Server app is presently configured to speak

- "Apollo Server HTTP" (name invented by me) for queries and mutations over HTTP (maybe compatible with the newer ["GraphQL over HTTP" spec](https://github.com/graphql/graphql-over-http/blob/73e67a41b9d3b7ee16a8031e09f077795f1a3286/README.md); not sure); and
- `graphql-ws`, referring not to this repo but rather the WebSocket subprotocol supported by and defined in subscriptions-transport-ws@0.9.18 ([src](https://github.com/apollographql/subscriptions-transport-ws/blob/c6fb351fe3d7c7a447438798fab43c268b33036e/src/protocol.ts#L1)).

I understand _this_ repo to be proposing a new subprotocol, `graphql-transport-ws`, and providing reference server and client implementations. After reviewing their specifications, which I'll identify by their subprotocol names—

1. [`graphql-ws`](https://github.com/apollographql/subscriptions-transport-ws/blob/c6fb351fe3d7c7a447438798fab43c268b33036e/PROTOCOL.md), from subscriptions-transport-ws
2. [`graphql-transport-ws`](https://github.com/enisdenjo/graphql-ws/blob/77a29812b415450806eccb704b01ded4eaf493c3/PROTOCOL.md), from graphql-ws (this project)

—I have a few questions about how to use this project:

1. Can you confirm that graphql-transport-ws is not cross-compatible with graphql-ws? For instance, I see that although a few message `type`s share the same name (e.g., `connection_init`), this newer subprotocol introduces new types like `subscription` that are central to its operation.
2. Would documentation demonstrating how to implement a server with support for both subprotocols be warranted? I'm kind of a newb with WebSockets, and I didn't realize until I saw your comment [here](https://github.com/graphql/graphql-over-http/pull/140#issuecomment-739823000) that there's a built-in way for client and server to negotiate the subprotocol. That's very cool and quells my concerns about migrating to a better, incompatible new subprotocol, if only I knew how to support both simultaneously.
3. Minor question: What was the motivation for [undocumenting](https://github.com/enisdenjo/graphql-ws/commit/99d05dc8a4a4d5112065e4af4a1b0ffc1d6480f1#diff-62d56fa1c25dda8d49ccdbf9ea31df4576f84625706d54613dff0acc8f974d97) the information about server-sent ping control frames as the intended method for keepalives? Before I went digging and learned about pings/pongs (cf. me being new to WebSockets), I was under the mistaken impression that if I used this protocol I'd have to hand-roll some kind of keepalive mechanism. Perhaps it's well-known to folks experienced with WebSockets, but in particular since folks migrating from subscriptions-transport-ws might be expecting to see that dealt with in the protocol itself, mentioning it in the docs might be especially warranted (if only to clarify/teach that it's not a feature gap in graphql-transport-ws; rather, the latter is just smarter about leveraging of stuff built into WebSockets!)

At an even higher level, my abstract feature request is to add to the README:

1. A comparison/constrating to GraphQL WebSockets subprotocols of yore, of which graphql-ws (the subprotocol) seems to be the de facto standard. Your [blog post](https://the-guild.dev/blog/graphql-over-websockets) mentioned a few specific things, which I think would be great to mention in this project's README in order to clearly position the project to people in a hurry. And then after motivating why the new thing is better...
2. A short discussion of migration from the highly-adopted-but-unmaintained old thing to the great new thing. To be fair, it is clear if one studies the recipes (which are **exquisite**, thank you!), but short of that it wasn't immediately clear to this backend dev whether this was _such_ a new protocol that my teammates consuming our API would be able to use this or not. Also, know that folks visiting the old thing are [explicitly directed here](https://github.com/apollographql/subscriptions-transport-ws/commit/76d9777f45823673cd57918df258cfc35aa81480#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3), so having a "landing page"/section speaking to them could be nice.

Thanks in advance for the answers to the three questions above. Also, let me know if you'd welcome a docs PR to the effect of the two bits of README feedback above and I'll work on that if I have time.

**Comment by enisdenjo** [comment]
Hey there! TL;DR this library by itself is not backwards compatible with `subscriptions-transport-ws` and it will never be.

> Can you confirm that graphql-transport-ws is not cross-compatible with graphql-ws? For instance, I see that although a few message types share the same name (e.g., connection_init), this newer subprotocol introduces new types like subscription that are central to its operation.

The `graphql-transport-ws` Protocol is in no way cross-compatible with `graphql-ws`. This new Protocol is a complete, better thought through, revamp with security and ease-of-use in mind. A rough, but correct, mapping is done by @casey-chow here: https://github.com/apollographql/apollo-ios/issues/1622#issuecomment-765682613.

> Would documentation demonstrating how to implement a server with support for both subprotocols be warranted? I'm kind of a newb with WebSockets, and I didn't realize until I saw your comment here that there's a built-in way for client and server to negotiate the subprotocol. That's very cool and quells my concerns about migrating to a better, incompatible new subprotocol, if only I knew how to support both simultaneously.

There already is a recipe about how to implement the server. Check out [ws server usage with subscriptions-transport-ws backwards compatibility](https://github.com/enisdenjo/graphql-ws#ws-backwards-compat).

The `sec-websocket-protocol` is used to transmit the subprotocol name, it can be used to decide which to use client side too. A quick explanation on how is: client tries connecting with `graphql-transport-ws` (this protocol), if the connection is denied with a close code `1002: Protocol Error`, try using `graphql-ws` (the legacy protocol). However, if the server is backwards compatible, there is no need for implementing this client side.

> Minor question: What was the motivation for undocumenting the information about server-sent ping control frames as the intended method for keepalives? Before I went digging and learned about pings/pongs (cf. me being new to WebSockets), I was under the mistaken impression that if I used this protocol I'd have to hand-roll some kind of keepalive mechanism. Perhaps it's well-known to folks experienced with WebSockets, but in particular since folks migrating from subscriptions-transport-ws might be expecting to see that dealt with in the protocol itself, mentioning it in the docs might be especially warranted (if only to clarify/teach that it's not a feature gap in graphql-transport-ws; rather, the latter is just smarter about leveraging of stuff built into WebSockets!)

Robustness and simplicity. The Protocol is about transport; all other, higher level decisions, are up to you. Pointed out by @hoangvvo here https://github.com/graphql/graphql-over-http/pull/140#issuecomment-719895979.

The `graphql-ws` (legacy protocol) is over-complicated IMHO, this is why you might get that feeling. I am of the strong opinion that you should understand the transport before using it, this protocol `graphql-transport-ws` is tailored to WebSockets.

> A comparison/constrating to GraphQL WebSockets subprotocols of yore, of which graphql-ws (the subprotocol) seems to be the de facto standard. Your blog post mentioned a few specific things, which I think would be great to mention in this project's README in order to clearly position the project to people in a hurry. And then after motivating why the new thing is better...

Having answered the previous question, I wouldnt pollute the main readme here with superfluous information (like the nuances and differences between the protocols). The readme is about getting started with this library. Another document, sure, I welcome you to push PRs about that. I understand the "in a hurry" part; however, you shouldn't ever be in hurry when it comes to something important like data transport.

I kinda' felt like explaining why this library is preferred should be done through clean code, fast issue resolution and merges of community PRs, lack of bugs under the issue tab, high frequency of new versions when fixes are implied. I personally decide for/against this way. Also, going to `subscriptions-transport-ws` will lead you back here.

> A short discussion of migration from the highly-adopted-but-unmaintained old thing to the great new thing. To be fair, it is clear if one studies the recipes (which are exquisite, thank you!), but short of that it wasn't immediately clear to this backend dev whether this was such a new protocol that my teammates consuming our API would be able to use this or not. Also, know that folks visiting the old thing are explicitly directed here, so having a "landing page"/section speaking to them could be nice.

Thats completely fair and understandable. I just dont have much free time and I dont wish spending it on diffing the legacy library and Protocol, I'd rather push PRs to Apollo superseding the legacy library - however, any PRs are absolutely welcome!

I hope I have answered your questions in a direct and clear matter - thank you for bringing up this discussion.

Given free time from your side (or anyone reading this), I am welcoming any clarification PRs. But, please, keep them scarce, I'd rather have people (and you) push PRs to others replacing the legacy library, instead of documenting which one is "better" and how to decide here.

**Comment by spencerwilson** [comment]
Thanks! All clear.
