### ISSUE TITLE
Is there any option to make all requests in a single ws connection?

### ISSUE THREAD

**Issue by jjjuk** [enisdenjo/graphql-ws#168]
### Is there any option to make all requests in a single **ws** connection?

Hello everyone! With examples we have now in this repo, **graphql-ws** makes new **ws** connection for every **graphql** operation. 
(am I wrong?) 👀  
But is there any option to make them in a single handshake? 
Everything probably would work faster, because It would not send http handshake all the times.

If it's possible, could you give me an example, please? 
I'm not as experienced with this technologies as you, so It's hard to me to find the right approach.

If It isn't, I think this would be a fine improvement for this project! 

Thank you very match!

_P.S. I ❤️ opensource and what you do guys!_

**Comment by enisdenjo** [comment]
Hey there, actually you're wrong 😬. Once you create a client using `createClient`, all operations made using the `client.subscribe` will go through a **single** WebSocket connection.

Thanks for the kind words and no worries, we're all here to learn!

Just out of curiosity, what made you think a new WS connection will be made on each operation?

**Comment by jjjuk** [comment]
Thank you for answer! This is kind of behavior I've got with [apollo client example](https://github.com/enisdenjo/graphql-ws#apollo-client) and with [promise](https://github.com/enisdenjo/graphql-ws#promise) too.

![image](https://user-images.githubusercontent.com/61079830/115987883-9a529b00-a5e9-11eb-8e9d-38f0d3deecaa.png)

For every mutation I've got new connection with new `Sec-WebSocket-Key` header.

Server implementation is pretty simple `useServer()`
The only settings I provide to `ws.Server()` is `port` and `path`

**Comment by enisdenjo** [comment]
The client is `lazy` by default, meaning it creates a WebSocket connection on-demand (connects on first subscribe, disconnects on last unsubscribe). Since youre doing short lived mutations, the connection establishes on mutation start and disconnects when you get the result - having the client create a new connection on each operation.

Simply set [the client `lazy` option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.clientoptions.md#lazy) to `false` to create and persist the WS connection as soon as the client is created.

**Comment by jjjuk** [comment]
It works! Thank you! I think I'm closing this one)
