### ISSUE TITLE
WebSocket protocol error occured. It was most likely caused due to an unsupported subprotocol "graphql-ws" requested by the client

### ISSUE THREAD

**Issue by anthonyatp** [enisdenjo/graphql-ws#182]
I know this issue was already opened (#164) but I'm having the same problem and I don't have `subscription-transport-ws` installed.

I'm using `graphql-ws` version `^4.5.0`.

I'm setting this up with `apollo-server-express` and `type-graphql`. This issue comes up when running a subscription in the graphql playground.

Here's how my server is set up:
```ts
const app = express();
const apolloServer = new ApolloServer({ schema });

apolloServer.applyMiddleware({ app });

const port = process.env.PORT || 4000;  

const server = app.listen(port, () => {

    const wsServer = new ws.Server({
      server,
      path: "/graphql",
    });

    useServer({ schema }, wsServer);
  });
```

Any idea's what could be wrong?

Thanks!

**Comment by enisdenjo** [comment]
This is not a server issue, it is just a warning communicating that the WebSocket subprotocol requested by the client is not supported. In your case, simply because [`graphql-playground` uses the `subscriptions-transport-ws` library for subscriptions.](https://github.com/graphql/graphql-playground/blob/60f90a910f6df590c6c87cf3f8922a4f61ef454e/packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts#L3)

**Comment by anthonyatp** [comment]
Ahh ok understood - thanks for you're quick reply!
