### ISSUE TITLE
Getting WebSocket connection to 'ws://localhost:7080/query' failed on connecting graphql-ws client with gqlgen golang server

### ISSUE THREAD

**Issue by sagg155** [enisdenjo/graphql-ws#185]
**Screenshot**
![image](https://user-images.githubusercontent.com/12156593/119374834-b2483800-bcd7-11eb-9ace-e4f5268a0dfb.png)

**Expected Behaviour**
Should have connected with server but failed

**Actual Behaviour**
but instead it give WebSocket connection to 'ws://localhost:7080/query' failed 

**Debug Information**
Issue mentioned on stackoverflow
https://stackoverflow.com/questions/67675102/getting-websocket-connection-to-ws-localhost7080-query-failed-on-connecting

**Comment by enisdenjo** [comment]
Hey there! A close event code `1006` indicates abrupt closure, in this case, due to the server terminating the connection.

If you are talking about [this `gqlgen`](https://gqlgen.com/), it does not support the GraphQL over WebSocket protocol this library implements. [It, sadly, supports only the legacy protocol of `subscriptions-transport-ws`.](https://github.com/99designs/gqlgen/blob/5ad012e3d7be1127706b9c8a3da0378df3a98ec1/graphql/handler/transport/websocket.go#L65) Meaning, you must use the [`subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws) with their backend.

You should maybe open an issue on their side since only they can resolve this.

**Comment by sagg155** [comment]
@enisdenjo , yeah i have used this gqlgen only but here in L65 of above github link it's written this "Sec-Websocket-Protocol": []string{"graphql-ws"}, so here it's mentioned graphql-ws. Am i understanding something wrong. So, what the meaning of this line "Sec-Websocket-Protocol": []string{"graphql-ws"},

**Comment by enisdenjo** [comment]
Seems like there is already an [issue](https://github.com/99designs/gqlgen/issues/1430) and an accompanying [PR](https://github.com/99designs/gqlgen/pull/1507) over at `gqlgen`.

**Comment by enisdenjo** [comment]
The subprotocol of [GraphQL over WebSocket Protocol is `graphql-transport-ws`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#communication).

**Comment by sagg155** [comment]
@enisdenjo , thanks for helping, i was really frustated since last two days for this. I'll try subscriptions-transport-ws with this

**Comment by enisdenjo** [comment]
Sure thing, glad I could help. Best of luck!

**Comment by theogravity** [comment]
> The subprotocol of [the new GraphQL over WebSocket Protocol is `graphql-transport-ws`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#communication), `graphql-ws` belongs to `subscriptions-transport-ws`.

The comment is a bit confusing. Do you mean that graphql-ws is using the graphql-transport-ws protocol, and the package name was formerly subscriptions-transport-ws?

**Comment by enisdenjo** [comment]
The subprotocol of the new [GraphQL over WebSocket Protocol is `graphql-transport-ws`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#communication).
