### ISSUE TITLE
Graphql-ws opens a new Websocket connection instead of reusing existing one?

### ISSUE THREAD

**Issue by gnut-neygun** [enisdenjo/graphql-ws#307]
I link the Apollo client to this library according to the README.file and try to send 2 consecutive queries. I'm expecting to get only one WebSocket Connection which sends two subscribe messages in it, instead I get three.

![Screenshot from 2022-02-14 16-56-44](https://user-images.githubusercontent.com/36769488/153899031-f51bffed-33aa-4ab3-be1a-f32c71cfc520.png)

Is this intended behavior? If we open a new Websocket connection for each query, doesn't that defeat the purpose of using a websocket?

**Comment by enisdenjo** [comment]
Can you please share your client code?

**Comment by gnut-neygun** [comment]
```Typescript
// for Apollo Client v3:
import {
    ApolloLink,
    Operation,
    FetchResult,
    Observable, ApolloClient, InMemoryCache,
} from '@apollo/client/core';

import { print } from 'graphql';
import { createClient, ClientOptions, Client } from 'graphql-ws';
import {gql} from "@apollo/client/core";
class WebSocketLink extends ApolloLink {
    private client: Client;

    constructor(options: ClientOptions) {
        super();
        this.client = createClient(options);
    }

    public request(operation: Operation): Observable<FetchResult> {
        return new Observable((sink) => {
            return this.client.subscribe<FetchResult>(
                { ...operation, query: print(operation.query) },
                {
                    next: sink.next.bind(sink),
                    complete: sink.complete.bind(sink),
                    error: sink.error.bind(sink),
                },
            );
        });
    }
}

const link = new WebSocketLink({
    url: 'ws://localhost:8007/graphql',
    lazy: true
});

const client = new ApolloClient({
    uri: 'http://localhost:8007/graphql',
    link: link,
    cache: new InMemoryCache()
});

(async () => {
    let result = await client
    .query({
        query: gql`
            { dashboards {
                id, name
            }
            }
        `
    })
    console.log(result);
    result = await client
    .query({
        query: gql`
            { dashboard(id: 1) {
                id, name
            }
            }
        `
    })
    console.log(result);
}) ();

```
![Screenshot from 2022-02-14 20-03-39](https://user-images.githubusercontent.com/36769488/153929310-b0380f1e-ec63-44d5-8085-c84575748cb5.png)
![Screenshot from 2022-02-14 20-04-59](https://user-images.githubusercontent.com/36769488/153929426-6dc0cf6b-e946-4ec3-963a-14cee273bc1b.png)





I also tried the variant with Promise, same thing. The other socket:

**Comment by enisdenjo** [comment]
The 2nd screenshot is not from `graphql-ws`, probably your dev server.

Please screenshot me the two connections made on the `/graphql` route.

**Comment by gnut-neygun** [comment]
![Screenshot from 2022-02-15 02-19-35](https://user-images.githubusercontent.com/36769488/153974553-5b929326-3f28-47bc-8d80-072ac632e6e7.png)
![Screenshot from 2022-02-15 02-19-27](https://user-images.githubusercontent.com/36769488/153974559-b77cfac3-3ac2-45ca-83a0-efa1b921b51d.png)
These two are from the same session.

**Comment by enisdenjo** [comment]
Ok, I see now.

You're running the client in [`lazy: true` mode](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#lazy) making the client connect on-demand (connect on first operation, disconnect on last complete).

Looking at your examples, you're running the queries in series, the 2nd connection is opened because the 1st one is completed and therefore closed:
```ts
(async () => {
    // 👇 awaits for the query to complete
    let result = await client
    .query({
        query: gql`
            { dashboards {
                id, name
            }
            }
        `
    })

    // 👇 query is completed, no more queries running, close the connection
    console.log(result);

    // 👇 awaits for the next query to complete
    // since the connection was previously closed, this subscription will open a new one
    result = await client
    .query({
        query: gql`
            { dashboard(id: 1) {
                id, name
            }
            }
        `
    })
    console.log(result);
}) ();
```

You have a few options here:
1. Create the client with [`lazy: false`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#lazy), this will create a WS connection as soon as you create the client and will keep it alive until the [client gets disposed](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.Client.md#dispose).
2. Configure [`lazyCloseTimeout: 1000`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#lazyclosetimeout) option to set the disconnect timeout of 1 second. Meaning, the client will wait for 1 second after the last operation completes before closing the connection in lazy mode, if another operation executes in the meantime, the connection will not be closed.

**Comment by gnut-neygun** [comment]
Hi,
Thanks for your answer. I set it to lazy mode because I had the problem (with lazy by default false) initially so I looked around the configurations and thought setting lazy to true might solve the problem, but it didn't.

But your second suggestion works. Is there a way to keep it alive indefinitely, because lazy:false does not seem to be working.

**Comment by Amantel** [comment]
Wow, that's a great thread! 
Can we add it to the docs? In FAQ question, or something.

**Comment by Amantel** [comment]
> If you're asking whether the actual WebSocket connection will stay - no, it is bound to the process that created it.

That's what I was asking, thanks :)

**Comment by chris-parker-switchboard** [comment]
Thank you for the explanation on this issue.  I was seeing the same thing and this was a huge help!
