### ISSUE TITLE
Async connectionParams at request time

### ISSUE THREAD

**Issue by felixlucien** [enisdenjo/graphql-ws#344]
### Issue

We supply the authentication token while the request is being made for the http case, this comes in the form of a `Token` http header.

For the WS case, we wish to supply authentication information (preferably when we first subscribe to the subscription), this is because when the GraphQLWsLink is created, the user has not logged in yet and hence we have no token to supply.

Is there a way of doing some WS equivalent:

~~~
const authLink = new ApolloLink(async (operation, forward) => {
  // Mint the token
  const token = createToken();

  // Use the setContext method to set the HTTP headers.
  operation.setContext({
    headers: {
      authorization: token ? `Bearer ${token}` : "",
    },
  });

  // Call the next link in the middleware chain.
  return forward(operation);
});
~~~

What we're after is some way to do something like this:

~~~diff
const wsLink = new GraphQLWsLink(
  createClient({
    url: graphqWSlURL,
      // Called sometime after we've had the chance to log the user in.
+    buildConnectionParams: () => {
+        // Mint the token
+        const token = createToken();
+        return {
+            authorization: token ? `Bearer ${token}` : "",
+        }
+    }
      //The user isn't logged in yet
-    connectionParams: {
-      authorization: //we dont have the token yet :(
-    },
  })
);
~~~

Maybe there's a way to do this that I don't know about?

**Comment by felixlucien** [comment]
Looks like you can supply an async function, cheers!

**Comment by KillerCodeMonkey** [comment]
@enisdenjo but it seems the connectionParams function is only executed once the client is initilized?

I have short living tokens and are refreshing them for each request/connection. Is there a way the connection params are set again on each new connection?

**Comment by enisdenjo** [comment]
@KillerCodeMonkey the `connectionParams` is indeed [executed on every connection](https://github.com/enisdenjo/graphql-ws/blob/77682cd3d9bac748b5b24e2f8cf88e1d98c7a448/src/client.ts#L663-L669). For them to re-execute, you of course must close the socket first and therefore cause a new connection.

Is this not the case? If not, it's a serious bug and I'd appreciate new issue with a repro describing the broken behaviour - will fix it ASAP!

**Comment by KillerCodeMonkey** [comment]
Short question: When did the client creates a new connection. What i need is, that i can pass those params more on "subscription" base. not at first connect.

**Comment by enisdenjo** [comment]
`connectionParams` are for connecting, they're only executed during the connection phase. You can consult the ["ws server and client auth usage with token expiration, validation and refresh" recipe](https://github.com/enisdenjo/graphql-ws#auth-token) for a token management example.

Personally, I never kick the client off, active WebSocket connections cannot be hijacked - the identity of the client will remain unchanged during the lifecycle of the connection. However, I highly recommend always closing the connection if you deem the client's unauthorized simply because having the client go through the connecting phase again, and resubscribing, is the most secure way of guaranteeing auth safety.

Alternatively, if you still want to keep the connection alive and re-authenticate within, I'd go by using the [Ping/Pong messages](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#ping) and transmitting new credentials through the `payload` field.

**Comment by KillerCodeMonkey** [comment]
thanks, i will check it again.

**Comment by enisdenjo** [comment]
> Because the connection seem like not closed and reconnected.

The client should automatically disconnect after all subscriptions have been completed when running in [`lazy` mode](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#lazy) (which is the default).

> but in general after the server closes the connection the client should reconnect automatically?

Yes, and resubscribe all active subscriptions.

> but i have queries/subscriptions that do not need authentication. how to work with this?

I'd recommend separating the connection into 2 clients. One for anons and the other one for authenticated users. You'll of course have to adapt the server too, the easiest way would be to use the `onSubscribe` hook instead of `onConnect` and authenticate depending on the requested subscriptions (skip token check for public ones, do the check for private).

> Is there the possibility to close the connection through an Apollo error link?

Of course, roughly:
```diff
+ let activeSocket = null;
const wsLink = new GraphQLWsLink(
  createClient({
    connectionParams: async () => {
      const token = await getAndRefreshToken(endpointUri);

      console.log(token, 'ConnectionParams');

      return { authorization: token ? `Bearer ${token}` : '' };
    },
    url: endpointUri.replace(/^http/, 'ws'),
+   on: {
+     opened: (socket) => {
+       activeSocket = socket;
+     },
+     closed: (socket) => {
+       activeSocket = null;
+     },
+   },
  }),
);

+ // ...somewhere where you need it...
+ activeSocket.close(1001, 'Going Away'); // do note that the client will automatically reconnect after close!
```

**Comment by KillerCodeMonkey** [comment]
seems to work... wonderful dude! you are the man :D

i added a custom error link for ws. there i check, if i got my graphql error, that the user should be logged in. and then close the socket + set a flag for a custom retryWait handler. Because when trying to reconnect with refreshed token, i do not want a wait time.

HINT: i got a plain Browser WebSocket instance in "on: opened" not one of GraphQLWS WebSocket. So there are no parameters to pass, to the close method

**Comment by enisdenjo** [comment]
Awesome, glad you got it working!

> HINT: i got a plain Browser WebSocket instance in "on: opened" not one of GraphQLWS WebSocket. So there are no parameters to pass, to the close method

[Browser native WebSocket does indeed accept the close code and reason parameters.](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#parameters)

**Comment by KillerCodeMonkey** [comment]
strange, but the global typing says "no" in my ide, and when i try it, i get the error, that the method takes no parameter.

**Comment by KillerCodeMonkey** [comment]
Last thing only for completion: that error is coming, when passing reason as number and reason as string to socket.close()

```
A parameter or an operation is not supported by the underlying object
```
