### ISSUE TITLE
Customization of operations id

### ISSUE THREAD

**Issue by Amareis** [enisdenjo/graphql-ws#398]
### Story

As a client I often look at webscoket messages and cannot easily identify which subscription result is coming - or even distinguish it from recent mutation/queries.

![image](https://user-images.githubusercontent.com/4806617/189678149-fe468a21-d4db-451b-80ae-5dd128786802.png)

So I want possibility to generate operation ids based on some metadata. Even just operationName + some random will be much better for debugging. `payload.query.split(/[({]/)[0]` + some random will be even better.

### Acceptance criteria

- client is able to form operation ids based on subscribe payload (using `generateID`) or even just set it in payload directly.

**Comment by enisdenjo** [comment]
The [`generateID` client option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#generateid) intentionally does not take arguments to avoid ID collisions since [the server must close the socket if an ID collision occurs](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#subscribe).

But, I guess this should not restrict the implementor from generate custom IDs using whatever metadata...

Guess adding the payload as the first argument of `generateID` would help - I'll take a look. 👍

**Comment by Amareis** [comment]
BTW, operations ids should be unique only per-connection? That's not really clear from protocol and docs. If I just make incrementing counter (just like in subscriptions-transport-ws), will it work with multiply clients?

**Comment by enisdenjo** [comment]
Yes, operation IDs are unique per-connection.

**Comment by Amareis** [comment]
That's sweet! I think such customization even can be referenced in docs.

![image](https://user-images.githubusercontent.com/4806617/190637940-6c8ada38-e0a8-427d-a1e7-fe2a4ed4c414.png)
![image](https://user-images.githubusercontent.com/4806617/190638001-d34530f4-5187-4c64-9c17-f92175dbdc50.png)
