### ISSUE TITLE
Malfunctioning code in Client usage with Apollo doc

### ISSUE THREAD

**Issue by Peracek** [enisdenjo/graphql-ws#48]
In readme file, section "Client usage with Apollo".
The spread operator on `sink` object does not work for me. The client throws an error that the `next` function is undefined. Assigning the properties explicitly works (see the code snippet).
I wonder why is this happening, probably some prototype-related magic that is not clear to me.

```
public request(operation: Operation): Observable<FetchResult> {
    return new Observable((sink) => {
      return this.client.subscribe<FetchResult>(
        { ...operation, query: print(operation.query) },
        {
          // ...sink,
          next: sink.next,
          complete: sink.complete,

          error: (err) => {
            if (err instanceof Error) {
              sink.error(err);
            } else if (err instanceof CloseEvent) {
              sink.error(
                new Error(
                  `Socket closed with event ${err.code}` + err.reason
                    ? `: ${err.reason}` // reason will be available on clean closes
                    : '',
                ),
              );
            } else {
              // GraphQLError[]
              sink.error(
                new Error(err.map(({ message }) => message).join(', ')),
              );
            }
          },
        },
      );
    });
  }
```

**Comment by enisdenjo** [comment]
Nice catch! You're right, the recipe does not work. The reason why the sink does not spread is because its not an object! The subscriber (sink) that the Observable provides in the constructor is a class, its actually an instance of [zen-observable SubscriptionObserver](https://github.com/zenparsing/zen-observable/blob/328fb66a99242900c0fd4a330e9ff66ecfa3a887/src/Observable.js#L190-L196).
