### ISSUE TITLE
Recommended method of sending a bearer token

### ISSUE THREAD

**Issue by justtonytone** [enisdenjo/graphql-ws#90]
We would like to send a bearer token with all of our websocket messages. I know we can add this underneath payload, but this seems more like metadata to me and might fit nice at the top level (next to type and payload).

What do people think of adding an optional `authorization` key at the top level (or perhaps a way for users to add in custom top level keys?).

I'm thinking something like: 
```json
{
   "type":"connection_init",
   "authorization":"BEARER_TOKEN_HERE"
}
```

```json
{
   "id":"4a4ef089-b43c-447f-9746-0de97f4753c9",
   "type":"subscribe",
   "authorization":"BEARER_TOKEN_HERE",
   "payload":{
      "query":"subscription ...",
      "variables":{
         "..."
      },
      "operationName":"..."
   }
}
```

**Comment by enisdenjo** [comment]
Hey hey. The auth metadata goes beyond the scope of GraphQL and this library. Since this lib is a reference implementation of [the GraphQL over WebSocket Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) it holds the bear necessities. As you mentioned, the recommended way of supplying additional details for subscription requests is through the `payload`.

In my honest opinion, I would not recommend sending an auth token on every subscription message. Not only because the size of the message transmitted would increase unnecessarily; but I also feel that it would never be necessary to do something like this. Maybe I am missing something, can you elaborate a bit more on why exactly you would want this?

Furthermore, you can validate the auth token whenever you want in the backend, though! [Check this custom auth recipe out.](https://github.com/enisdenjo/graphql-ws#ws-auth-handling) If you need the client to refresh the token or re-authenticate - you are safe to close the connection and the client will automatically retry connecting - picking up the refreshed token along the way. Also, you may use the [`retryWait`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/_client_.clientoptions.md#retrywait) ([check the retry strategy recipe too](https://github.com/enisdenjo/graphql-ws#retry-strategy)) client option to time your retries and avoid spamming the server.

**Comment by justtonytone** [comment]
Hey Denis,

Thanks for the response. After thinking about it, I agree, sending the auth token on the subscription message is not necessary. So the recommended way of handling this would be to send the auth token with the connection init method, and then re-authenticate in the background whenever necessary?

**Comment by enisdenjo** [comment]
Of course, glad I could help!

Yeah, you pretty much summed it up. The Protocol is liberal enough to allow any kind of auth: Cookies, HTTP headers, messages within the socket, etc. However, my recommended way of doing auth is through the `ConnectionInit` message. [You can read about my take on using HTTP or Cookies in this comment.](https://github.com/graphql/graphql-over-http/pull/140/#issuecomment-703109328)

In my production environments I send the token over the init message and re-evaluate it on every subscribe. If the server detects that the token is invalid - it would immediately close the connection. Often enough, the token was already refreshed - so immediately on next reconnection attempt the client will send a fresh token and the server will allow the connection. Together with this, I send an "initial" event on every subscription which will fill in the gap of potential data losses while the client was away - safely simulating a reauth request.

**Comment by louisholley** [comment]
Hey @enisdenjo, we're trying to implement the auth refreshing you provide in your recipe which seems to work great, but I'm not sure how to handle data losses while the client reconnects. I can see in your last message in this thread you say:
> Together with this, I send an "initial" event on every subscription which will fill in the gap of potential data losses while the client was away - safely simulating a reauth request.

could you please elaborate what you mean by sending "an initial event on every subscription" here? thanks so much!

**Comment by enisdenjo** [comment]
> could you please elaborate what you mean by sending "an initial event on every subscription" here? thanks so much!

@louisholley sure, I'll give you an example:

Say you're subscribing to the progress of a file upload, what you're listening for are changes in the progress percentage (0%..10%..60%...100%). If the connection breaks and the upload finishes in the meantime (progress is 100%) and then the client reconnects - data loss will occur, the client wouldn't notice the progress made while disconnected.

In order to remedy this, you simply send an "initial" event on subscribe. This time, if the same as above happens, the client will get the initial event (with the current progress state) as soon as he reconnects with the latest progress percentage.

**Comment by louisholley** [comment]
ah i see, thanks so much for taking the time to explain! our use case is slightly more involved - it's essentially a chat app with one subscription listening to incoming messages for all of the user's conversations, so the "initial" event here would be all messages from all conversations right? i can't think of a solution to this other than having some queue that stores the events with a TTL and on subscribe pulls relevant messages out of this queue...

anyway, thanks again for taking the time to answer and thanks so much for your great work with `graphql-ws`!

**Comment by enisdenjo** [comment]
Yeah your case is a bit tricky. I guess you're emitting subscription events on each new message - meaning, an initial event wont help simply because a client might've missed more messages then just the latest one.

I can think of two potential solutions on the spot:
1. Hook on the [client's connect event](https://github.com/enisdenjo/graphql-ws/blob/master/docs/modules/client.md#eventconnected) and query for the list of all messages each time the client (re)connects
1. You guessed it - build a queue for missed events that drains on reconnect. Beware though, this is not as simple as it may seem, you have to understand and take care of a lot of moving parts to keep performance and security in par. `graphql-ws` itself does not ship with this queue exactly because it's too complicated for achieving a one-fits-all solution. **However,** I am very confident the queue can be built **on top** of `graphql-ws`.

I recommend the 1st approach, no doubt. No queue, no cache, no keeping subscriptions alive, no TTL, no memory leaks and no security implications.

Still, if your brave enough to endeavor into the depths of the 2nd approach - I'd be happy to give you pointers in case you get stuck! 😄

**Comment by louisholley** [comment]
@enisdenjo we're going with option 1 for now, as option 2 seems too scary at this point...but we might look into it further down the road. In any case, super grateful for your help & advice - thanks so much man!
